## Exercício

Você é um analista de RH e tem os salários de todos os funcionários da sua empresa em um array NumPy. Seu trabalho é identificar quantos funcionários ganham acima da média. Use o seguinte array para sua análise: `salarios = np.array([3000, 2500, 3500, 4000, 2000, 4500, 3000, 3800, 4800])`.

In [1]:
import numpy as np

salarios = np.array([3000, 2500, 3500, 4000, 2000, 4500, 3000, 3800, 4800])

media_salarial = np.mean(salarios)
print(media_salarial)


3455.5555555555557


In [4]:
acima_media = np.where(salarios > media_salarial)
print(acima_media)

print(salarios[salarios > media_salarial])

(array([2, 3, 5, 7, 8]),)
[3500 4000 4500 3800 4800]


In [7]:
qtd_func_acima = np.sum(salarios > media_salarial)
print(f"{qtd_func_acima} funcionários possuem salário acima da média.")

5 funcionários possuem salário acima da média.


### Bônus

Outras formas de fazer contagem


In [11]:
# Conte não zero
print(np.count_nonzero(salarios > media_salarial))

# Único
print(np.unique(salarios > media_salarial))
print(np.unique(salarios > media_salarial, return_counts=True))

# E por ser uma Tupla, poso fazer o unpack dela
valores_unicos, contagem = np.unique(salarios > media_salarial, return_counts=True)
print(valores_unicos)
print(contagem)


5
[False  True]
(array([False,  True]), array([4, 5]))
[False  True]
[4 5]


### Bônus 2

Criando 20 valores fictícios de salarios com a mesma faixa anterior, tomando cuidado de outras pessoas gerem os mesmo valores

In [16]:
rng = np.random.default_rng(seed=42)

salarios_gerados = rng.integers(low=np.min(salarios), high=np.max(salarios), size=20)
print(salarios_gerados)

[2249 4167 3832 3228 3212 4404 2240 3952 2564 2263 3474 4731 4060 4131
 4008 4200 3437 2358 4351 3261]


In [19]:
rng = np.random.default_rng(seed=42)

salarios_gerados = rng.integers(low=np.min(salarios), high=np.max(salarios), size=20, endpoint=True)
print(salarios_gerados)

[2249 4167 3833 3229 3212 4404 2240 3953 2564 2263 3474 4732 4060 4131
 4009 4201 3437 2358 4352 3261]


In [20]:
print(np.mean(salarios_gerados))

3506.45


In [21]:
# As funções estáticas também podem ser chamadas como métodos dos arrays
print(salarios_gerados.min())
print(salarios_gerados.max())
print(salarios_gerados.mean())

2240
4732
3506.45
